// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: svc_health.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *VersionRequest) Validate() error {
	return nil
}
func (this *VersionResponse) Validate() error {
	return nil
}
func (this *LivenessRequest) Validate() error {
	return nil
}
func (this *LivenessResponse) Validate() error {
	return nil
}
func (this *ToggleReadinessRequest) Validate() error {
	return nil
}
func (this *ToggleReadinessResponse) Validate() error {
	return nil
}
func (this *ReadinessRequest) Validate() error {
	return nil
}
func (this *ReadinessResponse) Validate() error {
	return nil
}
